const CareerRecommendation = require("../models/CareerRecommendation");
const { generateWithGemini } = require("../services/aiService");


// ==========================================
// TRUE AI CAREER RECOMMENDATION (Gemini)
// ==========================================

const generateCareerRecommendation = async (req, res) => {

    try {

        const {
            skills,
            interests,
            education,
            experience,
            careerGoal
        } = req.body;


        // ==========================================
        // VALIDATION
        // ==========================================

        if (
            !skills ||
            !interests ||
            !education
        ) {

            return res.status(400).json({
                message:
                    "Skills, interests and education are required"
            });

        }


        // ==========================================
        // TRUE AI GENERATION (Gemini)
        // Falls back to keyword logic if no API key
        // ==========================================

        const aiResult = await generateWithGemini({
            skills,
            interests,
            education,
            experience: experience || "",
            careerGoal: careerGoal || ""
        });

        const recommendations = aiResult.recommendations;


        // Remove duplicates and ensure 3-5 results

        const uniqueRecommendations = [
            ...new Set(recommendations)
        ].slice(0, 5);


        // ==========================================
        // SAVE RESULT
        // ==========================================

        const careerRecommendation =
            new CareerRecommendation({

                user: req.user.id,

                skills,

                interests,

                education,

                experience,

                careerGoal,

                recommendations:
                    uniqueRecommendations

            });


        await careerRecommendation.save();


        // ==========================================
        // RESPONSE
        // ==========================================

        res.status(200).json({

            message:
                aiResult.isTrueAI
                    ? "Career recommendations generated by Gemini AI"
                    : "Career recommendations generated successfully",

            recommendations:
                uniqueRecommendations,

            details: aiResult.details || [],

            isTrueAI: aiResult.isTrueAI,

            source: aiResult.source,

            data: careerRecommendation

        });


    } catch (error) {

        console.log(
            "Career Recommendation Error:",
            error
        );

        res.status(500).json({

            message:
                "Failed to generate career recommendations",

            error: error.message

        });

    }

};


// ==========================================
// GET MY CAREER RECOMMENDATIONS
// ==========================================

const getMyCareerRecommendations = async (req, res) => {

    try {

        const recommendations =
            await CareerRecommendation
                .find({
                    user: req.user.id
                })
                .sort({
                    createdAt: -1
                });


        res.status(200).json({

            message:
                "Career recommendations fetched successfully",

            recommendations

        });


    } catch (error) {

        console.log(
            "Get Career Recommendations Error:",
            error
        );

        res.status(500).json({

            message:
                "Failed to fetch career recommendations",

            error: error.message

        });

    }

};


module.exports = {

    generateCareerRecommendation,
    getMyCareerRecommendations

};