const Quiz = require("../models/Quiz");

// ======================================
// CREATE QUIZ
// ======================================

const createQuiz = async (req, res) => {
    try {
        const {
            course,
            lesson,
            question,
            options,
            correctAnswer
        } = req.body;

        if (
            !course ||
            !question ||
            !options ||
            !correctAnswer
        ) {
            return res.status(400).json({
                message: "All quiz fields are required"
            });
        }

        const quiz = await Quiz.create({
            course,
            lesson,
            question,
            options,
            correctAnswer
        });

        res.status(201).json({
            message: "Quiz created successfully",
            quiz
        });

    } catch (error) {

        console.log("Create Quiz Error:", error);

        res.status(500).json({
            message: "Failed to create quiz",
            error: error.message
        });
    }
};


// ======================================
// GET QUIZZES BY COURSE
// ======================================

const getQuizzesByCourse = async (req, res) => {
    try {

        const { courseId } = req.params;

        const quizzes = await Quiz.find({
            course: courseId
        })
        .populate("lesson")
        .sort({ createdAt: 1 });

        res.status(200).json({
            message: "Quizzes fetched successfully",
            quizzes
        });

    } catch (error) {

        console.log("Get Quiz Error:", error);

        res.status(500).json({
            message: "Failed to fetch quizzes",
            error: error.message
        });
    }
};


// ======================================
// GET SINGLE QUIZ
// ======================================

const getQuizById = async (req, res) => {
    try {

        const { quizId } = req.params;

        const quiz = await Quiz.findById(quizId)
            .populate("lesson");

        if (!quiz) {
            return res.status(404).json({
                message: "Quiz not found"
            });
        }

        res.status(200).json({
            message: "Quiz fetched successfully",
            quiz
        });

    } catch (error) {

        console.log("Get Single Quiz Error:", error);

        res.status(500).json({
            message: "Failed to fetch quiz",
            error: error.message
        });
    }
};


// ======================================
// UPDATE QUIZ
// ======================================

const updateQuiz = async (req, res) => {
    try {

        const { quizId } = req.params;

        const quiz = await Quiz.findByIdAndUpdate(
            quizId,
            req.body,
            {
                new: true,
                runValidators: true
            }
        );

        if (!quiz) {
            return res.status(404).json({
                message: "Quiz not found"
            });
        }

        res.status(200).json({
            message: "Quiz updated successfully",
            quiz
        });

    } catch (error) {

        console.log("Update Quiz Error:", error);

        res.status(500).json({
            message: "Failed to update quiz",
            error: error.message
        });
    }
};


// ======================================
// DELETE QUIZ
// ======================================

const deleteQuiz = async (req, res) => {
    try {

        const { quizId } = req.params;

        const quiz = await Quiz.findByIdAndDelete(quizId);

        if (!quiz) {
            return res.status(404).json({
                message: "Quiz not found"
            });
        }

        res.status(200).json({
            message: "Quiz deleted successfully"
        });

    } catch (error) {

        console.log("Delete Quiz Error:", error);

        res.status(500).json({
            message: "Failed to delete quiz",
            error: error.message
        });
    }
};


// ======================================
// GENERATE AI SKILL QUIZ (Gemini)
// ======================================

const generateAiQuiz = async (req, res) => {
    try {
        const { topic, skills, difficulty, count } = req.body;
        const { generateSkillQuiz } = require("../services/aiService");
        const result = await generateSkillQuiz({
            topic: topic || "General",
            skills: skills || [],
            difficulty: difficulty || "Intermediate",
            count: Math.min(Math.max(Number(count) || 5, 3), 10)
        });
        res.status(200).json({
            message: result.isTrueAI ? "Quiz generated by Gemini AI" : "Quiz generated (fallback)",
            questions: result.questions,
            isTrueAI: result.isTrueAI,
            source: result.source
        });
    } catch (error) {
        console.log("Generate AI Quiz Error:", error);
        res.status(500).json({ message: "Failed to generate quiz", error: error.message });
    }
};

// ======================================
// EVALUATE QUIZ ANSWERS
// ======================================

const evaluateQuiz = async (req, res) => {
    try {
        const { questions, answers } = req.body;
        if (!questions || !answers || questions.length !== answers.length) {
            return res.status(400).json({ message: "Questions and answers required" });
        }
        let score = 0;
        const results = questions.map((q, i) => {
            const correct = q.correctAnswer?.trim() === answers[i]?.trim();
            if (correct) score++;
            return { index: i, question: q.question, selected: answers[i], correctAnswer: q.correctAnswer, explanation: q.explanation, isCorrect: correct };
        });
        const percentage = Math.round((score / questions.length) * 100);
        let level = "Beginner";
        if (percentage >= 80) level = "Advanced";
        else if (percentage >= 50) level = "Intermediate";
        res.status(200).json({ message: "Quiz evaluated", score, total: questions.length, percentage, level, results });
    } catch (error) {
        res.status(500).json({ message: "Failed to evaluate quiz", error: error.message });
    }
};

module.exports = {
    createQuiz,
    getQuizzesByCourse,
    getQuizById,
    updateQuiz,
    deleteQuiz,
    generateAiQuiz,
    evaluateQuiz
};